"""Add email field to users table

Revision ID: 5654cab09dc4
Revises: 3b1e2c9d7f40
Create Date: 2026-03-18 16:25:21.806953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5654cab09dc4'
down_revision: Union[str, Sequence[str], None] = '3b1e2c9d7f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if email column already exists to make migration idempotent
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    if 'users' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('users')]
        if 'email' not in columns:
            op.add_column('users', sa.Column('email', sa.String(), nullable=False, server_default=''))
            # Remove the default after adding the column
            op.alter_column('users', 'email', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
