"""create tasks table

Revision ID: c589e5628da2
Revises: 
Create Date: 2026-03-16 17:25:47.057332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c589e5628da2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if table already exists to make migration idempotent
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    if 'tasks' not in inspector.get_table_names():
        op.create_table(
            'tasks',
            sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('title', sa.String(), nullable=False),
            sa.Column('description', sa.String(), nullable=True),
            sa.Column('completed', sa.Boolean(), nullable=True, server_default=sa.text('false')),
            sa.PrimaryKeyConstraint('id')
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
    pass
    # ### end Alembic commands ###
